apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-ingress
spec:
  rules:
  - host: embloy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: core-front
            port:
              number: 80
  - host: genius.embloy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: genius-front
            port:
              number: 80
  - host: api.embloy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: core-service
            port:
              number: 80
  - host: api2.embloy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: genius-service
            port:
              number: 80
