PreCommit:
  Brakeman:
    enabled: true
  RuboCop:
    enabled: true
  BundleAudit:
    enabled: true
  RailsBestPractices:
    enabled: false
  RubySyntax:
    enabled: true
  YamlSyntax:
    enabled: true
PrePush:
  RSpec:
    enabled: true
#CommitMsg:
#  TextWidth:
#    enabled: true
#  SpellCheck:
#    enabled: true
