# .rubocop.yml
AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable 
  Include:
    - '**/*.rb'
  Exclude:
Layout/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/ClassLength:
  Enabled: false
Lint/SuppressedException:
  Enabled: true