path:
  - results
id: job_slug
title:
  - title
  - position
descriptionHtml: description\body
departmentName: job_type
locationIds: fetch\https://api.ashbyhq.com/location.info\ASHBY_API_KEY\post\json\locationId\location
publishedDate: created_at
updatedAt: updated_at
externalLink: referrer_url
applicationFormDefinition\sections\*A*0*fields:
  application_options:
    - isRequired: required






