apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        "kubernetes.azure.com/mode": system
      containers:
      - name: core-service
        image: embloy.azurecr.io/embloy-core:latest
        ports:
        - containerPort: 3000
          name: core-service
        resources:
          requests:
            cpu: 1m
            memory: 150Mi
          limits:
            cpu: 75m
            memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: core-service
