# core-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: core
  name: core
spec:
  type: NodePort
  ports:
  - name: "core-api"
    port: 3000
    targetPort: 80
    nodePort: 31000
  selector:
    app: core
