name: Trigger auto deployment for embloy-core

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/embloy-core-AutoDeployTrigger-dcebf20c-6ed1-40f7-baad-23e67faeedb1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EMBLOYCORE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EMBLOYCORE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EMBLOYCORE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: embloy.azurecr.io
          registryUsername: ${{ secrets.EMBLOYCORE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EMBLOYCORE_REGISTRY_PASSWORD }}
          containerAppName: embloy-core
          resourceGroup: embloy_core
          imageToBuild: embloy.azurecr.io/embloy-core:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


